name: Build, Test, and Publish Mosquitto

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mosquitto-custom:latest .

    - name: Test Mosquitto container
      run: |
        docker run -d --name mosquitto-test -p 1883:1883 -p 9001:9001 ${{ secrets.DOCKERHUB_USERNAME }}/strinder-mosquitto:latest
        sleep 5
        docker logs mosquitto-test
        docker ps | grep mosquitto-test
        docker stop mosquitto-test
        docker rm mosquitto-test

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/strinder-mosquitto:latest